/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Comuna;
import Clases.Provincia;
import Clases.Region;
import Clases.Sucursal;
import ConectorBD.Conexion;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicolas
 */
public class interfaceSucursal extends javax.swing.JFrame {
    PreparedStatement ps;
    ResultSet rs;
    /**
     * Creates new form interfaceSucursal
     */
    public void Limpiar(){
        
        txtDireccion.setText(null);
        txtEmail.setText(null);
        txtTelefono.setText(null);
        cbComuna.removeAllItems();
        cbProvincia.removeAllItems();
        cbRegion.setSelectedItem("Seleccione Region");
        
        
    }
    public boolean isEmail(String correo){
// Patrón para validar el email
        Pattern pattern = Pattern
                .compile("^[\\w\\\\\\+]+(\\.[\\w\\\\]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$");
 
        // El email a validar
        
 
        Matcher mather = pattern.matcher(correo);
 
        if (mather.find() == true) {
            return true;
        } else {
            return false;
        }
}
    public void DatosTabla(){
        PreparedStatement ps, prep;
        ResultSet rs, res;
        Connection conn = Conexion.getConnection();
        DefaultTableModel model = (DefaultTableModel) tableSucursal.getModel();
        model.addColumn("ID");
        model.addColumn("Nombre Sucursal");
        model.addColumn("Direccion");
        model.addColumn("Correo");
        model.addColumn("Comuna");


        try {
            String sql = "select id_sucursal, nombre_sucursal, direccion_sucursal,correo_sucursal, fk_comuna from sucursal";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
   
                
            while (rs.next()) {

                prep = conn.prepareStatement("select * from comuna where comuna_id="+rs.getString("fk_comuna"));
                res = prep.executeQuery();
                while (res.next()) {
                               model.addRow(new Object[]{rs.getString("id_sucursal"), rs.getString("nombre_sucursal"), rs.getString("direccion_sucursal"), 
                rs.getString("correo_sucursal"), res.getString("comuna_nombre")});
                }

            }
   
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error :"+e.toString());

        }
        
    }
    public void Actualizar(){
        
        
        DefaultTableModel model = new DefaultTableModel();
        tableSucursal.setModel(model);
        try{
        PreparedStatement ps = null;
        ResultSet rs = null;
        Conexion con = new Conexion();
        Connection conn = con.getConnection();
        String sql = "SELECT * FROM sucursal";
        ps = conn.prepareStatement(sql);
        rs = ps.executeQuery();
        ResultSetMetaData rsMd = rs.getMetaData();
        int cant = rsMd.getColumnCount();
        model.addColumn("ID");
        model.addColumn("Nombre Sucursal");
        model.addColumn("Direccion");
        model.addColumn("Correo");
        model.addColumn("ID Comuna");
        while(rs.next()){
            Object[] filas = new Object[cant];
            for ( int i = 0 ; i<cant; i++){
                filas[i] = rs.getObject(i+1);          
            }
          model.addRow(filas);  
        }
        
        } catch (SQLException e){
            
        }
        
        
    }
    
    public interfaceSucursal() {
        initComponents();
        DatosTabla();
        idLabel.setText(Integer.toString(Sucursal.idIncrement()));
        
        Region a = new Region();
        DefaultComboBoxModel modelRegion = new DefaultComboBoxModel(a.mostrarRegiones());
        cbRegion.setModel(modelRegion);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btAgregar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSucursal = new javax.swing.JTable();
        txtDireccion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cbRegion = new javax.swing.JComboBox<>();
        cbProvincia = new javax.swing.JComboBox<>();
        cbComuna = new javax.swing.JComboBox<>();
        idLabel = new javax.swing.JLabel();
        btLimpiar1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btActualizar = new javax.swing.JButton();
        Buscador = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btFiltrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sucursal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 808, 51));

        jLabel6.setText("Region");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 187, 48, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 68, 818, 19));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Agregar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 87, -1, -1));

        jLabel4.setText("ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 128, 48, -1));

        jLabel5.setText("Direccion");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 156, 62, -1));

        jLabel7.setText("Telefono");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 307, 48, -1));

        btAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btAgregar.setText("AGREGAR");
        btAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 388, -1, -1));

        jLabel8.setText("Correo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 276, 48, -1));

        btEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEliminar.setText("ELIMINAR");
        btEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btEliminarMouseClicked(evt);
            }
        });
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 371, -1, 40));

        tableSucursal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableSucursal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, 214));

        txtDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDireccionFocusLost(evt);
            }
        });
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 153, 198, -1));

        jLabel13.setText("Provincia");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 214, 48, -1));

        jLabel14.setText("Comuna");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 245, 48, -1));

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 304, 198, -1));

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 273, 198, -1));

        cbRegion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRegionItemStateChanged(evt);
            }
        });
        cbRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRegionActionPerformed(evt);
            }
        });
        getContentPane().add(cbRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 184, 199, -1));

        cbProvincia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbProvinciaItemStateChanged(evt);
            }
        });
        getContentPane().add(cbProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 211, 199, -1));

        cbComuna.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbComunaItemStateChanged(evt);
            }
        });
        getContentPane().add(cbComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 242, 198, -1));
        getContentPane().add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 128, 56, 14));

        btLimpiar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLimpiar1.setText("LIMPIAR");
        btLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 388, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("MODIFICAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 371, -1, 40));

        btActualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btActualizar.setText("ACTUALIZAR");
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 371, -1, 40));

        Buscador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BuscadorFocusLost(evt);
            }
        });
        Buscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscadorActionPerformed(evt);
            }
        });
        Buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BuscadorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscadorKeyTyped(evt);
            }
        });
        getContentPane().add(Buscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 198, -1));

        jLabel9.setText("Id");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 34, -1));

        btFiltrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btFiltrar.setText("FILTRAR");
        btFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFiltrarActionPerformed(evt);
            }
        });
        getContentPane().add(btFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarActionPerformed
         if(txtDireccion.getText().equals("")||txtEmail.getText().equals("")||txtTelefono.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
            
        }
         else{
             try{
             PreparedStatement prs;
             Conexion c = new Conexion();
             Connection reg = c.getConnection();
             String idsuc = idLabel.getText();
             Comuna com = (Comuna) cbComuna.getSelectedItem();
             String idcom = Integer.toString(com.getId_comuna());
             ps = reg.prepareStatement("INSERT into sucursal(id_sucursal,direccion_sucursal, correo_sucursal, fk_comuna) values("+idsuc+",?,?,"+idcom+")");
             ps.setString(1, txtDireccion.getText());
             ps.setString(2, txtEmail.getText());  
             prs = reg.prepareStatement("INSERT into telefonos_sucursal (id_telefonos_sucursal, numero, fk_sucursal) values("+Sucursal.idIncrementTelSuc()+",?,"+idsuc+")");
             int res = ps.executeUpdate();
             if (res>0) {
                int a = Integer.parseInt(idLabel.getText())+1;
                idLabel.setText(Integer.toString(a));
                JOptionPane.showMessageDialog(null, "Registro Agregado con éxito");
                Limpiar();
                Actualizar();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Error al ingresar datos");
                Limpiar();
               
            }
            reg.close();
            
             } catch (Exception e){
                 JOptionPane.showMessageDialog(null, "error : "+e.toString());
             } 
         }
            
        
    }//GEN-LAST:event_btAgregarActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
        
        int fila = tableSucursal.getSelectedRowCount();
        if (fila < 1 ){
            JOptionPane.showMessageDialog(null, "Seleccione un registro de la tabla");
        } else{
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if (respuesta == 0){
            Sucursal.Eliminardato(tableSucursal.getValueAt(tableSucursal.getSelectedRow(),0).toString());
      
            }
        }
        
        
        
        
    }//GEN-LAST:event_btEliminarActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
        
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese caracteres validos","Error", JOptionPane.ERROR_MESSAGE);
         
     }
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
      
        
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
    if (evt.getKeyCode() == evt.VK_ENTER)  { 
        if (txtEmail.getText().length()>40){
            JOptionPane.showMessageDialog(null, "El largo no debe ser superior a 40", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if (!(Pattern.matches("^[\\w\\\\\\+]+(\\.[\\w\\\\]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$"
                , txtEmail.getText()))) 
{           
            JOptionPane.showMessageDialog(null, "Ingrese Email Valido", "Error", JOptionPane.ERROR_MESSAGE);
           }
        else{
            txtTelefono.requestFocus();
        }
        
    }   
       
        
        
        
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
     char c = evt.getKeyChar();
       
      if(Character.isLetter(c))
     {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error", JOptionPane.ERROR_MESSAGE);
       
     }
     else if((int)evt.getKeyChar()>=32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error", JOptionPane.ERROR_MESSAGE);
         
     }        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void cbRegionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRegionItemStateChanged
       
        if (evt.getStateChange() == ItemEvent.SELECTED){
            Region reg = (Region) cbRegion.getSelectedItem();
            Provincia prov = new Provincia();
            DefaultComboBoxModel modProvincia = new DefaultComboBoxModel(prov.mostrarProvincias(reg.getId_region()));
            cbProvincia.setModel(modProvincia);
            cbComuna.removeAllItems();
        }
        
        
    }//GEN-LAST:event_cbRegionItemStateChanged

    private void cbComunaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbComunaItemStateChanged
        
        
    }//GEN-LAST:event_cbComunaItemStateChanged

    private void cbProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbProvinciaItemStateChanged
      
          if (evt.getStateChange() == ItemEvent.SELECTED){
            Provincia prov = (Provincia) cbProvincia.getSelectedItem();
            Comuna com = new Comuna();
            DefaultComboBoxModel modComuna = new DefaultComboBoxModel(com.mostrarComunas(prov.getId_provincia()));
            cbComuna.setModel(modComuna);
            
        }
        
        
        
    }//GEN-LAST:event_cbProvinciaItemStateChanged

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
      
           
        if (!(Pattern.matches("^[\\w\\\\\\+]+(\\.[\\w\\\\]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$"
                , txtEmail.getText()))) 
{           
            JOptionPane.showMessageDialog(null, "Ingrese Email Valido", "Error", JOptionPane.ERROR_MESSAGE);
           }
        else{
            txtTelefono.requestFocus();
        }
        
     
        
        
        
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionFocusLost
       
       
    }//GEN-LAST:event_txtDireccionFocusLost

    private void txtDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyPressed
      if (evt.getKeyCode() == evt.VK_ENTER){
        if(txtDireccion.getText().length()>50){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "El largo no debe ser superior a 50","Error", JOptionPane.ERROR_MESSAGE);
        }
      }  
    }//GEN-LAST:event_txtDireccionKeyPressed

    private void btLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiar1ActionPerformed
        Limpiar();
    }//GEN-LAST:event_btLimpiar1ActionPerformed

    private void btEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEliminarMouseClicked
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if (respuesta == 0){
            
        }
        
        
    }//GEN-LAST:event_btEliminarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        modSucursal s = new modSucursal();
        s.setVisible(true);
        s.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
       
        DatosTabla();
        
    }//GEN-LAST:event_btActualizarActionPerformed

    private void BuscadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BuscadorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscadorFocusLost

    private void BuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscadorActionPerformed

    private void BuscadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscadorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscadorKeyPressed

    private void BuscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscadorKeyTyped
        char c = evt.getKeyChar();
       
      if(Character.isLetter(c))
     {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error", JOptionPane.ERROR_MESSAGE);
       
     }
     else if((int)evt.getKeyChar()>=32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error", JOptionPane.ERROR_MESSAGE);
         
     }  
    }//GEN-LAST:event_BuscadorKeyTyped

    private void btFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFiltrarActionPerformed
       
        
        
    }//GEN-LAST:event_btFiltrarActionPerformed

    private void cbRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRegionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaceSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaceSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaceSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaceSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaceSucursal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buscador;
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btAgregar;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btFiltrar;
    private javax.swing.JButton btLimpiar1;
    private javax.swing.JComboBox<String> cbComuna;
    private javax.swing.JComboBox<String> cbProvincia;
    private javax.swing.JComboBox<String> cbRegion;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tableSucursal;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
